spring:
  security:
    oauth2:
       client:
        registration:
          default:
            client-name: Default
            client-id: YOUR-CLIENT-ID-HERE
            client-secret: YOUR-CLIENT-SECRET-HERE
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: 
              - openid
              - profile
        provider:
          default:
            authorization-uri: https://test-idp.olevi.fi/idp/profile/oidc/authorize
            token-uri: https://test-idp.olevi.fi/idp/profile/oidc/token
            user-info-uri: https://test-idp.olevi.fi/idp/profile/oidc/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://test-idp.olevi.fi/idp/profile/oidc/keyset
